# Generated by Django 3.2.5 on 2022-10-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20221026_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=13.99, max_digits=10),
            preserve_default=False,
        ),
    ]
