# Generated by Django 4.1.6 on 2023-02-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_restaurantlocation_street_useradress'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradress',
            name='apartment',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
