# Generated by Django 4.1.6 on 2023-02-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_useradress_apartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
