# Generated by Django 4.1.3 on 2022-11-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_order_place_remove_restaurant_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quanity_for_order',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
