# Generated by Django 4.1.3 on 2022-11-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_item_quanity_for_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quanity_for_order',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
    ]
