# Generated by Django 4.1.6 on 2023-02-25 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_orderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(blank=True, to='base.orderitem'),
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='items',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.item'),
        ),
    ]
