# Generated by Django 4.1.3 on 2022-11-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_order_deliver_address_order_delivery_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='deliver_address',
            new_name='street',
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
