# Generated by Django 4.1.3 on 2022-11-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_deliver_address_order_street_order_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('food', 'Available to borrow'), ('drink', 'Borrowed by someone')], default='food', max_length=32),
        ),
    ]
