# Generated by Django 4.1.3 on 2022-12-02 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_item_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quanity_for_order',
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('food', 'food'), ('drink', 'drink')], default='food', max_length=32),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quanity_for_order', models.DecimalField(decimal_places=0, max_digits=2)),
                ('items', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.item')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='base.orderitem'),
        ),
    ]
