# Generated by Django 4.1.3 on 2022-12-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_item_quanity_for_order_alter_item_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='type',
            field=models.CharField(choices=[('Asian', 'Asian'), ('Italian', 'Italian'), ('Gregorian', 'Gregorian'), ('America', 'American'), ('Polish', 'Polish')], default='default', max_length=32),
        ),
    ]
