# Generated by Django 4.1.3 on 2022-12-20 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_restaurant_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='value',
            field=models.CharField(choices=[('$', 1), ('$$', 2), ('$$$', 3)], default='default', max_length=32),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='type',
            field=models.CharField(choices=[('Asian', 'Asian'), ('Italian', 'Italian'), ('Gregorian', 'Gregorian'), ('American', 'American'), ('Polish', 'Polish')], default='default', max_length=32),
        ),
    ]
